nav:
  Home: /home/
  About: /about/
  Writing: /archives/
  Tag: /tags/
  Category: /categories/
  Search: /search/
  Projects: https://github.com/gcl-head/hexo-blog

projects_url: https://github.com/gcl-head/hexo-blog

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/gcl-head
        twitter: https://twitter.com/SpaIITEwjtarBt4
        instagram: https://www.instagram.com/bbiggesthead/
        linkedin: https://www.linkedin.com/in/%E8%91%A1%E8%90%84-%E5%A4%A7-3256a5203/
    post_count: 5
    highlight: monokai

# keept it like this to add the root path (probably a bug)
root: ..

solar:
    # factor between 0 (fast), 1(normal), 2(very slow)  
    speed: 1
    sun_image: /images/sun.png
    earth_image: /images/earth.png
    jupiter_image: /images/jupiter.png
    mars_image: /images/mars.png
    mercury_image: /images/mercury.png
    shadow_image: /images/shadow.png
    venus_image: /images/venus.png

# RSS
rss: true

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: G-28H2E71SQB # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
